package gift.domain;

public enum CategoryType {
    GIFT_CARD,
    GIFT_CERTIFICATE,
    BEAUTY,
    FASHION,
    FOOD,
    HOME_LIVING_BOOK,
    LEISURE_SPORT,
    ARTIST_CHARACTER,
    BABY_PET,
    DIGITAL_APPLIANCE,
    KAKAO_FRIENDS,
    TREND_GIFT,
    DEPARTMENT_STORE
}
