spring:
  application:
    name: spring-gift
  datasource:
    url: jdbc:h2:mem:testdb # H2 데이터베이스 URL
    driver-class-name: org.h2.Driver # H2 데이터베이스 드라이버
    username: sa
  h2:
    console:
      enabled: true # H2 console 활성화 여부
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 업데이트
    show-sql: true # 실행되는 SQL 쿼리 로깅
  sql:
    init:
      mode: always # SQL 초기화 모드

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
jwt:
  secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
