INSERT INTO Category (color, description, imageUrl, name) VALUES ('#FF5733', 'Description for 교환권', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '교환권');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#33FF57', 'Description for 상품권', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '상품권');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#3357FF', 'Description for 뷰티', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '뷰티');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#FF33A1', 'Description for 패션', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '패션');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#A133FF', 'Description for 식품', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '식품');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#FF3333', 'Description for 리빙/도서', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '리빙/도서');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#33FF33', 'Description for 레저/스포츠', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '레저/스포츠');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#3333FF', 'Description for 아티스트/캐릭터', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '아티스트/캐릭터');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#FFA133', 'Description for 유아동/반려', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '유아동/반려');
INSERT INTO Category (color, description, imageUrl, name) VALUES ('#A1FF33', 'Description for 디지털/가전', 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', '디지털/가전');

INSERT INTO Member (email, password, role) VALUES ('user1@kakao.com', 'pw1', 'USER');
INSERT INTO Member (email, password, role) VALUES ('user2@kakao.com', 'pw2', 'USER');
INSERT INTO Member (email, password, role) VALUES ('user3@kakao.com', 'pw3', 'USER');
INSERT INTO Member (email, password, role) VALUES ('user4@kakao.com', 'pw4', 'USER');
INSERT INTO Member (email, password, role) VALUES ('admin@kakao.com', 'admin', 'ADMIN');

INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Espresso', 1000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 1);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Americano', 2000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 2);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Latte', 3000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 3);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Cappuccino', 4000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 4);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Macchiato', 5000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 5);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Mocha', 6000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 6);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Flat White', 7000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 7);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Affogato', 8000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 8);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Cortado', 9000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 9);
INSERT INTO Product (name, price, imageUrl, category_id) VALUES ('Irish Coffee', 10000, 'https://cdn.psnews.co.kr/news/photo/202401/2044098_92432_053.jpeg', 10);

INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 1);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 1);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 1);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 2);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 2);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 2);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 3);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 3);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 3);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 4);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 4);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 4);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 5);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 5);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 5);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 6);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 6);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 6);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 7);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 7);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 7);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 8);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 8);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 8);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 9);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 9);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 9);
INSERT INTO Option (name, quantity, product_id) VALUES ('Small', 100, 10);
INSERT INTO Option (name, quantity, product_id) VALUES ('Medium', 200, 10);
INSERT INTO Option (name, quantity, product_id) VALUES ('Large', 300, 10);


INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 1, 1);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 1, 2);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 2, 3);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 2, 4);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 3, 5);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 3, 6);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 4, 7);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 4, 8);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 5, 9);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 5, 10);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 1, 1);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 2, 2);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 3, 3);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 4, 4);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 5, 5);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 1, 6);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 2, 7);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Large', 3, 8);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Small', 4, 9);
INSERT INTO Wishlist (optionName, member_id, product_id) VALUES ('Medium', 5, 10);
