DROP TABLE IF EXISTS wish_lists;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS category;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          name VARCHAR(15) NOT NULL,
                          price INTEGER NOT NULL,
                          image_url VARCHAR(255) NOT NULL,
                          category_id BIGINT NOT NULL,
                          PRIMARY KEY (id)
);

CREATE TABLE wish_lists (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            member_id BIGINT NOT NULL,
                            product_id BIGINT NOT NULL,
                            PRIMARY KEY (id)
);

CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          name VARCHAR(255) NOT NULL,
                          PRIMARY KEY (id)
);