CREATE TABLE IF NOT EXISTS member (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      email VARCHAR(255) NOT NULL UNIQUE,
                                      password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       price INTEGER NOT NULL,
                                       name VARCHAR(15) NOT NULL,
                                       img_url VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS wish (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    member_id BIGINT NOT NULL,
                                    product_id BIGINT NOT NULL,
                                    CONSTRAINT fk_wish_member FOREIGN KEY (member_id) REFERENCES member(id),
                                    CONSTRAINT fk_wish_product FOREIGN KEY (product_id) REFERENCES product(id)
);